### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by dawei03896** [pedrovfigueiredo/frameintIFE#1]

**Comment by pedrovfigueiredo** [comment]
Hi dawei,

Thanks for your interest in our work!

The paper just got accepted for publication at WACV 2023, so I'll be working on both the project page and code upload this weekend/next week.
The goal is to have at least parts of it up by the end of next week (I'm targeting the test script with an example first, then I'll add instructions for training).

**Comment by noobtoob4lyfe** [comment]
Looking forward to this!

**Comment by pedrovfigueiredo** [comment]
Hi @noobtoob4lyfe and @dawei03896,
The source code for both optimizing and testing is now available in the main branch.
